env:
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: 5432
  
services:
  - docker

before_script:
  - docker-compose down

script:
  - docker-compose build
  - docker-compose up
  
after_script:
  - docker-compose down

deploy:
