env:
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: 5433 # Avoid bind: already in use from postgres service enabled by default in TravisCI.
  
services:
  - docker

before_script:
  - docker-compose run web npm run migrate
  - docker-compose up -d

script:
  - docker ps | grep -q node-postgres-docker_web
  
after_script:
  - docker-compose down

deploy:
