version: '3'
services:
  
  web:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "${DB_PORT}:5432"
